# Use version of Ubuntu which has cmake 2.8.12
sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cd build
  - cmake .. && make