notifications:
  email: false
language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: ppa:george-edison55/precise-backports
        packages:
        - gcc-5
        - g++-5
        - xorg-dev
        - libglu1-mesa-dev
        - cmake-data
        - cmake
    install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - os: osx
    compiler: clang
script:
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target package
deploy:
  provider: releases
  api_key:
    secure: slBCRTcrIlFvAn9eZwW+z7lhlWRyQF69EFox6VsKBCjk1fLGClf36Pkq2Ro18Dac5fy1HsOCtX9Q88UrnVKZFyrfWszCKXsirudLs1LZXVoSioMPT83BPKy418YTQvoeM9ZFU7u3k8Yt3Yw6w+4IAN78fUBJYMYtfXbCyAWWHs/ta8Jhzp2jhbvhKRZ7MwXtyC7czs6/R/lrBk6nZ4ajj/xtLolQdneunhxjrdbkCK7os43wzXSwzyNseSZdSBO9hZsxvkC/SEf+10Kp7MqBlATRTMmp4U4x7h8dWRpRjKgoelWakWFXCeye3nVuDrIcCs+jNivCgWcQ3nvwXn5c/LLGbV8HuWyL6N7XnP6V+z7q3l6djevZz27HQIP66va3lJiQpwDlpbUoroTlDbOXLaagTngyYPVV9Z386VsAkIIS6Jnmq2uLNNvnVtUM8xAcNdYOsS6BNpihlKRCOEyZHyib9a9Olwk8F7WduEfwmqEWz46I67cHocQfwXMPvAA0Rx4x3l+omZCZMJbW2ujU01oUyzsqzZ7NyEHQ8bog8DMDunpx0chxpG4JMG+1gObzlJG0G6TSLPac8+fu+Q8Ku2wmxmVLetxbuabeyJu6j7IgmP+GsmVbMu9v502sOaE45UXe6i3V3p16JmJxpx9kzQ/YmP5Jpxwxo3UOTiVnlEw=
  file: build/lowpoly3d-0.1.1-Linux.tar.gz
  on:
    repo: Kuxe/lowpoly3d
    tags: true
