# Use version of Ubuntu which has cmake 2.8.12
sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Update build toolchain
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
# Build steps
script:
  - cd build
  - cmake .. && make