# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Update build toolchain
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - xorg-dev
      - libglu1-mesa-dev
      - cmake
# Build steps
script:
  - cd build
  - cmake .. && make