# Use version of Ubuntu which has cmake 2.8.12
sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
#Download dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev
# Build steps
script:
  - cd build
  - cmake .. && make