image: Visual Studio 2015

# Credit for workaround goes to Jørgen Ibsen https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
# Workaround for CMake not wanting sh.exe on PATH for MinGW

install:
  choco install mingw --version 5.3.0

before_build:
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\tools\mingw64\bin;%PATH%

build_script:
  - cd build
  - cmake -G "MinGW Makefiles" ..
  - cmake --build .
  - cmake --build . --target package

deploy:
  description: 'Latest binaries and headers for lowpoly3d'
  provider: GitHub
  auth_token:
    secure: aY81dhM0dxmO1a3xpBrrY0DE6hkiBrlIkNj3REO//qqLN4sFJzD9kLwNS/ggAr8nIJHW9wwMwQPM3bAkCak9CL+njxE0F7a9yoDltqEEI4KvCtOoQATC9ZDfZZhMvOBV0wk0lhqTZTXsKURD7ie3qn7ICNQI9f8SkOQOcMeAEPXroyloY11fmPBbhsg+ftT9Cz8a4ku4Bryako2A+AnVX7nXdx4rFOaXGuLdMzV04T42i3+clPJkDmVYJBVSnEt4K3hupoGICu/Ec8AenHXcXqwaoXyWn4283yz/KSUsPEyBGB24eZ/lnrs6nFistQTPKqDjYF4uM589OBn7zoyHv14o7KX+kgl8KPLZPsiMEZH0Eu5/+9VCbhTfBYOlb+iPqJNLI9MSN16EF3+jKWo6u+qZGEThauc4exh3KqY79cb54hTQGRUk9cjjeqGCfwMd/oKyF7he9vF3dZdyPOh9sr1JnevGP3yOGgPl838AhnWUGPpfweGtO2lbk05cbD6FK9BEob3P/wG4J9nrGyvjbTsseqvSOt3NGotK4k3DEvtwQJrvM4ImaVzS/eLaQwyCbZZ3bcGOXRkcW0CfTv/kK5NS7Gilj0IzBiJ2OsjaZn/8o6CPTaGPVQTWXItuLzlmrSlpdsZG6T+//E2UghEGB7GVVwMPC+uZbp3pcRKEfZc=
  artifact: 'build/lowpoly3d-*.zip'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true