image: Visual Studio 2015

# Credit for workaround goes to Jørgen Ibsen https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
# Workaround for CMake not wanting sh.exe on PATH for MinGW

install:
  choco install mingw --version 5.3.0

before_build:
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\tools\mingw64\bin;%PATH%

build_script:
  - cd build
  - cmake -G "MinGW Makefiles" ..
  - cmake --build .
  - cmake --build . --target package
  - mv lowpoly3d*.zip ..
  - cd ..

deploy:
  description: 'Latest binaries and headers for lowpoly3d'
  provider: GitHub
  auth_token:
    secure: qpxxGP1vPIUbfG3zFl1dtqPi9Hsr8A+ldrPmAJGt8oaV6VmFb2JzHyf0nD+XJ0EQ
  artifact: 'lowpoly3d-*.zip'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true